#!/bin/bash
# Deploy reports to GitHub Pages

echo "📄 Deploying to GitHub Pages..."
echo ""

# Create gh-pages branch if not exists
git branch gh-pages 2>/dev/null || git checkout gh-pages

# Copy reports to root for GitHub Pages
cp -r frontend/reports/* .

# Create index.html with links
cat > index.html << 'HTML'
<!DOCTYPE html>
<html>
<head>
  <title>GeoVera Brand Intelligence Reports</title>
  <style>
    body { font-family: system-ui; max-width: 800px; margin: 50px auto; padding: 20px; }
    h1 { color: #2563eb; }
    ul { list-style: none; padding: 0; }
    li { margin: 15px 0; }
    a { color: #2563eb; text-decoration: none; font-size: 18px; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>🌍 GeoVera Brand Intelligence Reports</h1>
  <p>Click any report below to view:</p>
  <ul>
HTML

# Add links for all HTML files
for file in *.html; do
  if [ "$file" != "index.html" ]; then
    name=$(echo "$file" | sed 's/-/ /g' | sed 's/.html//' | sed 's/\b\(.\)/\u\1/g')
    echo "    <li>📊 <a href=\"$file\">$name</a></li>" >> index.html
  fi
done

cat >> index.html << 'HTML'
  </ul>
  <hr>
  <p style="color: #666; font-size: 14px;">Generated by GeoVera Intelligence Platform</p>
</body>
</html>
HTML

# Commit and push
git add .
git commit -m "Deploy reports to GitHub Pages"
git push origin gh-pages

echo ""
echo "✅ Deployed! Your reports will be available at:"
echo "   https://YOUR-USERNAME.github.io/geovera-staging/"
echo ""
echo "⚙️  Enable GitHub Pages:"
echo "   1. Go to repository Settings"
echo "   2. Pages section"
echo "   3. Source: gh-pages branch"
echo "   4. Save"
