#!/bin/bash
# Prepare folder for Netlify Drop

echo "📦 Preparing for Netlify Drop..."
echo ""

# Create deploy folder
rm -rf netlify-deploy
mkdir -p netlify-deploy

# Copy reports
cp frontend/reports/*.html netlify-deploy/

# Create index.html
cat > netlify-deploy/index.html << 'HTML'
<!DOCTYPE html>
<html>
<head>
  <title>GeoVera Reports</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 40px 20px;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: white;
      border-radius: 20px;
      padding: 40px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
    }
    h1 {
      color: #2d3748;
      font-size: 36px;
      margin-bottom: 10px;
    }
    .subtitle {
      color: #718096;
      margin-bottom: 40px;
      font-size: 18px;
    }
    .reports {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
      gap: 20px;
    }
    .report-card {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      border-radius: 12px;
      padding: 30px 20px;
      text-align: center;
      transition: transform 0.2s, box-shadow 0.2s;
      cursor: pointer;
    }
    .report-card:hover {
      transform: translateY(-5px);
      box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);
    }
    .report-card a {
      color: white;
      text-decoration: none;
      display: block;
    }
    .report-icon {
      font-size: 48px;
      margin-bottom: 15px;
    }
    .report-name {
      font-size: 20px;
      font-weight: 600;
    }
    .footer {
      margin-top: 50px;
      text-align: center;
      color: #a0aec0;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🌍 GeoVera Intelligence</h1>
    <div class="subtitle">Brand Intelligence Reports - Powered by AI</div>

    <div class="reports">
HTML

# Add report cards
for file in netlify-deploy/*.html; do
  if [ -f "$file" ] && [ "$(basename $file)" != "index.html" ]; then
    filename=$(basename "$file")
    name=$(echo "$filename" | sed 's/-/ /g' | sed 's/.html//' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1')
    echo "      <div class=\"report-card\">" >> netlify-deploy/index.html
    echo "        <a href=\"$filename\">" >> netlify-deploy/index.html
    echo "          <div class=\"report-icon\">📊</div>" >> netlify-deploy/index.html
    echo "          <div class=\"report-name\">$name</div>" >> netlify-deploy/index.html
    echo "        </a>" >> netlify-deploy/index.html
    echo "      </div>" >> netlify-deploy/index.html
  fi
done

cat >> netlify-deploy/index.html << 'HTML'
    </div>

    <div class="footer">
      Generated by GeoVera Intelligence Platform<br>
      Cost: $0.11 per report | 94% Brand Alignment | AI-Powered Insights
    </div>
  </div>
</body>
</html>
HTML

echo "✅ Folder ready: netlify-deploy/"
echo ""
echo "📤 Next steps:"
echo "   1. Go to https://app.netlify.com/drop"
echo "   2. Drag & drop the 'netlify-deploy' folder"
echo "   3. Get instant live URL!"
echo ""
echo "OR install Netlify CLI:"
echo "   npm install -g netlify-cli"
echo "   cd netlify-deploy && netlify deploy --prod"
